#define YOLO_ALL
#define YOLO_ANY
#define YOLO_ARRAY
#define YOLO_CHUNK
#define YOLO_CONCAT
#define YOLO_DICT
#define YOLO_EACH
#define YOLO_EXTEND
#define YOLO_FIND
#define YOLO_FIRST
#define YOLO_FLATMAP
#define YOLO_FLATTEN
#define YOLO_FMAP
#define YOLO_GET
#define YOLO_GROUPBY
#define YOLO_HAS
#define YOLO_INDEXOF
#define YOLO_INJECT
#define YOLO_JOIN
#define YOLO_LAST
#define YOLO_MAP
#define YOLO_MAX
#define YOLO_MIN
#define YOLO_NONE
#define YOLO_PARTITION
#define YOLO_PICK
#define YOLO_PLUCK
#define YOLO_PMAP
#define YOLO_POP
#define YOLO_PUSH
#define YOLO_REDUCE
#define YOLO_REVERSE
#define YOLO_ROTATE
#define YOLO_SAMPLE
#define YOLO_SELECT
#define YOLO_SHIFT
#define YOLO_SHUFFLE
#define YOLO_SKIP
#define YOLO_SLICE
#define YOLO_SNIP
#define YOLO_SORT
#define YOLO_SPLIT
#define YOLO_TRANSPOSE
#define YOLO_UNIQ
#define YOLO_UNSHIFT
#define YOLO_UPTO
#define YOLO_WITHOUT

#import "YOLO.h"
